
package com.vodafone.soap_consumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CardValidationWebServiceImplService", targetNamespace = "http://service.vodafone.com/", wsdlLocation = "http://localhost:8090/ws/CardValidation?wsdl")
public class CardValidationWebServiceImplService
    extends Service
{

    private final static URL CARDVALIDATIONWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARDVALIDATIONWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CARDVALIDATIONWEBSERVICEIMPLSERVICE_QNAME = new QName("http://service.vodafone.com/", "CardValidationWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/ws/CardValidation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDVALIDATIONWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CARDVALIDATIONWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CardValidationWebServiceImplService() {
        super(__getWsdlLocation(), CARDVALIDATIONWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CardValidationWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDVALIDATIONWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CardValidationWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CARDVALIDATIONWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CardValidationWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDVALIDATIONWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CardValidationWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardValidationWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardValidationWebService
     */
    @WebEndpoint(name = "CardValidationPort")
    public CardValidationWebService getCardValidationPort() {
        return super.getPort(new QName("http://service.vodafone.com/", "CardValidationPort"), CardValidationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardValidationWebService
     */
    @WebEndpoint(name = "CardValidationPort")
    public CardValidationWebService getCardValidationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.vodafone.com/", "CardValidationPort"), CardValidationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDVALIDATIONWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CARDVALIDATIONWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CARDVALIDATIONWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
